AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for creating a stack with a bucket and a DynamoDB table.
Resources:
    S3BucketForPoc:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: io.pratik.profileimages
    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: entities
          AttributeDefinitions:
            -
              AttributeName: "pk"
              AttributeType: "S"
          KeySchema:
            -
              AttributeName: "pk"
              KeyType: "HASH"
          ProvisionedThroughput:
             ReadCapacityUnits: 5
             WriteCapacityUnits: 5