version: '3.7'

services:

  postgres:
    container_name: "rds-hello-world"
    image: postgres
    volumes:
      - rds-hello-world:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello

volumes:
  rds-hello-world:
    driver: local