spring:
  datasource:
    url: jdbc:h2:./data/metadb
    username: admin
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
  # https://stackoverflow.com/questions/40057057/spring-boot-and-thymeleaf-hot-swap-templates-and-resources-once-again
  thymeleaf:
    cache: false
    templates_root: src/main/resources/templates/
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
    credentials:
      profile-name: dev

# https://docs.spring.io/spring-cloud-aws/docs/2.2.3.RELEASE/reference/html/#amazon-sdk-configuration
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
